ManagedUpload {
    _events: { },
    body: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 02 bc 00 00 01 ac 08 06 00 00 00 3f 84 74 45 00 00 01 7c 69 43 43 50 49 43 43 20 50 72 6f 66 69 ... 65847 more bytes >,
        sliceFn: [Function: slice],
            callback: [Function],
                parts: { },
    completeInfo: [],
        fillQueue: [Function: fillBuffer],
            partSize: 5242880,
                service: Service {
        config: Config {
            credentials: [Credentials],
                credentialProvider: [CredentialProviderChain],
                    region: 'us-east-1',
                        logger: null,
                            apiVersions: { },
            apiVersion: null,
                endpoint: 's3.amazonaws.com',
                    httpOptions: [Object],
                        maxRetries: undefined,
                            maxRedirects: 10,
                                paramValidation: true,
                                    sslEnabled: true,
                                        s3ForcePathStyle: false,
                                            s3BucketEndpoint: false,
                                                s3DisableBodySigning: true,
                                                    computeChecksums: true,
                                                        convertResponseTypes: true,
                                                            correctClockSkew: false,
                                                                customUserAgent: null,
                                                                    dynamoDbCrc32: true,
                                                                        systemClockOffset: 0,
                                                                            signatureVersion: 'v4',
                                                                                signatureCache: true,
                                                                                    retryDelayOptions: { },
            useAccelerateEndpoint: false,
                clientSideMonitoring: false,
                    endpointDiscoveryEnabled: false,
                        endpointCacheSize: 1000,
                            hostPrefixEnabled: true,
                                accessKeyId: 'AKIAWP5F2JV5ZRG6LDHL',
                                    secretAccessKey: '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',
                                        Bucket: 'labs14-miracle-messages-image-upload',
                                            constructor: [Function],
                                                getCredentials: [Function: getCredentials],
                                                    update: [Function: update],
                                                        loadFromPath: [Function: loadFromPath],
                                                            clear: [Function: clear],
                                                                set: [Function: set],
                                                                    keys: [Object],
                                                                        extractCredentials: [Function: extractCredentials],
                                                                            setPromisesDependency: [Function: setPromisesDependency],
                                                                                getPromisesDependency: [Function: getPromisesDependency],
                                                                                    params: [Object]
        },
        endpoint: Endpoint {
            protocol: 'https:',
                host: 's3.amazonaws.com',
                    port: 443,
                        hostname: 's3.amazonaws.com',
                            pathname: '/',
                                path: '/',
                                    href: 'https://s3.amazonaws.com/'
        },
        _events: { apiCallAttempt: [Array], apiCall: [Array] },
        MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
            CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
                _clientId: 2
    },
    totalBytes: 65897,
        failed: false,
            partPos: 5242880,
                isDoneChunking: true,
                    numParts: 1,
                        totalPartNumbers: 1,
                            singlePart: Request {
        domain: null,
            service: Service {
            config: [Config],
                endpoint: [Endpoint],
                    _events: [Object],
                        MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
                            CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
                                _clientId: 2
        },
        operation: 'putObject',
            params: {
            Body: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 02 bc 00 0001 ac 08 06 00 00 00 3f 84 74 45 00 00 01 7c 69 43 43 50 49 43 43 20 50 72 6f 66 69 ... 65847 more bytes >,
                Bucket: 'labs14-miracle-messages-image-upload',
                    Key: 'Screen Shot 2019-08-14 at 1.04.04 PM.png',
                        ContentType: undefined
        },
        httpRequest: HttpRequest {
            method: 'PUT',
                path: '/Screen%20Shot%202019-08-14%20at%201.04.04%20PM.png',
                    headers: [Object],
                        body: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 02 bc 00 0001 ac 08 06 00 00 00 3f 84 74 45 00 00 01 7c 69 43 43 50 49 43 43 20 50 72 6f 66 69 ... 65847 more bytes >,
                            endpoint: [Endpoint],
                                region: 'us-east-1',
                                    _userAgent: 'aws-sdk-nodejs/2.510.0 darwin/v12.8.0 callback',
                                        virtualHostedBucket: 'labs14-miracle-messages-image-upload',
                                            stream: [ClientRequest]
        },
        startTime: 2019 - 08 - 16T21: 04: 44.554Z,
            response: Response {
            request: [Circular],
                data: null,
                    error: null,
                        retryCount: 0,
                            redirectCount: 0,
                                httpResponse: [HttpResponse],
                                    maxRetries: 3,
                                        maxRedirects: 10
        },
        _asm: AcceptorStateMachine { currentState: 'send', states: [Object] },
        _haltHandlersOnError: false,
            _events: {
            validate: [Array],
                afterBuild: [Array],
                    restart: [Array],
                        sign: [Array],
                            validateResponse: [Array],
                                send: [Array],
                                    httpHeaders: [Array],
                                        httpData: [Array],
                                            httpDone: [Array],
                                                retry: [Array],
                                                    afterRetry: [Array],
                                                        build: [Array],
                                                            extractData: [Array],
                                                                extractError: [Array],
                                                                    httpError: [Array],
                                                                        beforePresign: [Array],
                                                                            success: [Array],
                                                                                complete: [Array],
                                                                                    httpUploadProgress: [Array]
        },
        emit: [Function: emit],
            API_CALL_ATTEMPT: [Function: API_CALL_ATTEMPT],
                API_CALL_ATTEMPT_RETRY: [Function: API_CALL_ATTEMPT_RETRY],
                    API_CALL: [Function: API_CALL],
                        _managedUpload: [Circular],
                            signedAt: 2019 - 08 - 16T21: 04: 44.566Z
    }
}